spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expiryTracker?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.app.expirytracker.model
  configuration:
    map-underscore-to-camel-case: true